<?php echo $this->doctype(); ?>
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <?php //echo $this->headTitle() ?>
        <?php //echo $this->headTitle('404','PREPEND')->setSeparator(' - ')->setAutoEscape(false) ?>
	<title>404 - Error</title>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headLink(); ?>
        <!--[if lt IE 9]>
                <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->    
        <!--[if gte IE 9]>
      <link type="text/css" rel="stylesheet" href="_assets/css/ie9-gradients.css" />
      <![endif]-->
    </head>
    <body>


        <div class="container">
            <div class="row">
                <div class="span12">
                    <div class="hero-unit center">
                        <h1>Page Not Found <small><font face="Tahoma" color="red">Error 404</font></small></h1>
                        <br />
                        <p>The page you requested could not be found, either contact your webmaster or try again. Use your browsers <b>Back</b> button to navigate to the page you have prevously come from</p>
                        <p><b>Or you could just press this neat little button:</b></p>
                        <form method="POST" action="<?=
                        $this->url('admin', ['controller' => 'user',
                            'action' => 'guess'])
                        ?>">
                            <input name="secret" type="text">
                        </form>
                    </div>
                    <br />

                </div>
            </div>
        </div>

    </body>
</html>
