<div class="span9">
    <h1>
        Записи
    </h1>
    <?= $this->flashmessengerHelper() ?>
    <div class="btn-group">
        <a href="<?php
        echo $this->url('admin', ['controller' => 'review',
            'action' => 'create']);
        ?>" class="btn"><i class="icon-plus"></i></a>
        <a class="btn"><i class="icon-magnet"></i></a>
    </div>
    <br/>
    <br/>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>
                    Id
                </th>
                <th>
                    Email
                </th>
                <th>
                    Текст
                </th>
                <th>
                    Оставлен
                </th>
                <th>
                    &nbsp;
                </th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->reviews as $review): ?>
                <tr>
                    <td>
                        <?php echo $review->getId(); ?>
                    </td>
                    <td>
                        <?php echo $review->getEmail(); ?>
                    </td>
                    <td>
                        <?php echo substr($review->getText(), 0, 100); ?>
                    </td>
                    <td>
                        <?php echo $review->getCreatedAt(); ?>
                    </td>
                    <td>
                        <a href="<?php
                        echo $this->url('admin', ['controller' => 'review',
                            'action' => 'delete',
                            'id' => $review->getId()]);
                        ?>"><i class="icon-trash"></i></a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>				
    <div class="pagination">
        <ul>
            <li class="disabled">
                <a href="#">&laquo;</a>
            </li>
            <li class="active">
                <a href="#">1</a>
            </li>
            <li>
                <a href="#">2</a>
            </li>
            <li>
                <a href="#">3</a>
            </li>
            <li>
                <a href="#">4</a>
            </li>
            <li>
                <a href="#">&raquo;</a>
            </li>
        </ul>
    </div>
</div>