<?php echo $this->headTitle($this->translate('Обо мне'), 'PREPEND')->setSeparator(' - ')->setAutoEscape(false) ?>
<div class="def-block clearfix">
    <h4> Всё обо мне </h4><span class="liner"></span>
    <p>Здравствуйте! Я рада видеть Вас на моем сайте!<br>
        Меня зовут Чупырь Таисия. Хочу рассказать Вам немного о себе.<br>
        Я творческий человек, как и многие люблю прекрасное.<br>
        Стать визажистом - было мечтой моей жизни.</p>
</div>