<div class="def-block clearfix">
    <h4> Contact With US </h4><span class="liner"></span>

    <div class="grid_6 mt">
        <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. </p>
        <p>It has survived not only five centuries, but also the leap into electronic typesetting.</p>
        <p>Phone: <strong> 001 00125548 </strong> <br> Email: <strong>info@remixmusic.com</strong></p>
    </div><!-- end grid6 -->

    <div class="grid_6 mt">
        <form action="http://theme20.com/demo/remix/processForm.php" id="contactForm" method="post">
            <div class="clearfix">
                <div class="grid_6 alpha fll"><input type="text" class="requiredField" placeholder="Name *" id="senderName" name="senderName"></div>
                <div class="grid_6 omega flr"><input type="text" class="requiredField email" placeholder="Email Address *" id="senderEmail" name="senderEmail"></div>
            </div>
            <div><textarea rows="8" class="requiredField" placeholder="Message *" id="message" name="message"></textarea></div>
            <input type="submit" value="Send Email" name="sendMessage" id="sendMessage">
            <span>  </span>
        </form><!-- end form -->
    </div><!-- end grid6 -->

</div>