<div class="span9">
    <h1>
        Категории
    </h1>
    <?= $this->flashmessengerHelper() ?>
    <div class="btn-group">
        <a
            href="<?php
        echo $this->url('admin', ['controller' => 'categories',
            'action' => 'create']);
        ?>" data-toggle="modal" data-target="#categorieEditModal" class="btn"><i class="icon-plus"></i></a>
        <a class="btn">Right</a>
    </div>
    <br/>
    <br/>
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>
                    Id
                </th>
                <th>
                    Название категории
                </th>
                <th>
                    &nbsp;
                </th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($categories as $categorie): ?>
                <tr>
                    <td>
                        <?php echo $categorie->getId(); ?>
                    </td>
                    <td>
                        <a href="#" ><?php echo $categorie->getCategorieName(); ?></a>
                    </td>
                    <td>
                        <a href="<?php
                        echo $this->url('admin', ['controller' => 'categories',
                            'action' => 'get',
                            'id' => $categorie->getId()]);
                        ?>" data-toggle="modal" data-target="#categorieEditModal"><i class="icon-edit"></i></a>
                        <a href="<?php
                        echo $this->url('admin', ['controller' => 'categories',
                            'action' => 'delete',
                            'id' => $categorie->getId()]);
                        ?>"><i class="icon-trash"></i></a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>				
</div>

<div class="modal fade hide" id="categorieEditModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" >
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h2>Категория</h2>
    </div>
    <div class="modal-body">
    </div>

</div>