<div class="row">
    <div class="span4">
        <div class="white-bg">
            <i class="icon-plus-sign icon-position"></i>
            <h4>Advanced Settings</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent tempus eleifend risus ut congue. 
                Pellentesque nec lacus elit. Mauris ornare tempor nulla.</p>
        </div><!--/white bg-->
    </div><!--/span4-->
    <div class="span4">
        <div class="white-bg">
            <i class="icon-dashboard icon-position"></i>
            <h4>User Dashboard</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent tempus eleifend risus ut congue. 
                Pellentesque nec lacus elit. Mauris ornare tempor nulla.</p>
        </div><!--/white bg-->
    </div><!--/span4-->
    <div class="span4">
        <div class="white-bg">
            <i class="icon-info-sign icon-position"></i>
            <h4>Top Notch Support</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent tempus eleifend risus ut congue. 
                Pellentesque nec lacus elit. Mauris ornare tempor nulla.</p>
        </div><!--/white bg-->
    </div><!--/span4-->
</div>