            <footer id="footer">
                <div class="footer-last">
                    <div class="row clearfix">
                        <span class="copyright">© 2013 by <a href="http://vk.com/cawakharkov">CawaKharkov</a>. All Rights Reserved. Powered by <span class="label label-important"><a href="https://github.com/zendframework/zf2">ZF_<?php echo Zend\Version\Version::VERSION; ?></a></span>.</span>
                        <div id="toTop"><i class="icon-angle-up"></i></div><!-- Back to top -->
                        <div class="foot-menu">
                            <ul>
                                <li><a href="index.html">Home</a></li>
                                <li><a href="mp3s.html">MP3</a></li>
                                <li><a href="videos.html">Video</a></li>
                                <li><a href="gallery.html">Photo Gallery</a></li>
                                <li><a href="blog.html">Blog</a></li>
                                <li><a href="contact.html">Contact</a></li>
                            </ul><!-- end links -->
                        </div><!-- end foot menu -->
                    </div><!-- row -->
                </div><!-- end last -->

            </footer><!-- end footer -->