<div id="white-content">
    <div class="container">
        <div class="row">
            <div class="span2">
                <h5>News Articles</h5>
            </div><!--/span2-->
            <div class="span5">
                <div class="icon-box pull-left">
                    <i class="icon-file"></i>
                </div><!--/icon box-->
                <div class="description">
                    <h5><a href="#">We've updated our application to make it faster.</a></h5>
                    <p class="muted"><i class="icon-calendar"></i>Oct. 17th, 2012 &nbsp; - &nbsp; 
                        <i class=" icon-comment-alt"></i> <a class="muted" href="#">4 Comments</a></p>
                </div><!--/pull right-->
            </div><!--/span5-->
            <div class="span5">
                <div class="icon-box pull-left">
                    <i class="icon-file"></i>
                </div><!--/icon box-->
                <div class="description">
                    <h5><a href="#">Push comes to shove, we got it done in time.</a></h5>
                    <p class="muted"><i class="icon-calendar"></i>Oct. 17th, 2012 &nbsp; - &nbsp; 
                        <i class=" icon-comment-alt"></i> <a class="muted" href="#">4 Comments</a></p>
                </div><!--/pull right-->
            </div><!--/span5-->
        </div><!--/row-->

        <hr>

        <div class="row">
            <div class="span2">
                <h5>Latest Tweets</h5>
            </div><!--/span2-->
            <div id="latest_tweets">

                <div id="jtwt3674" class="jtwt"><p style="display: none;" class="jtwt_loader muted">Loading Tweets...</p><div class="span5"><div class="icon-box pull-left"><i class="icon-twitter"></i></div><div class="description"><p>We also have several totally new themes on the way, the next one should be available sometime next week! <span class="muted">16 days ago</span></p></div></div><div class="span5"><div class="icon-box pull-left"><i class="icon-twitter"></i></div><div class="description"><p>Our Concrete5 theme, one of the first on ThemeForest, was released earlier this week. You can take a look at <a href="http://t.co/AHesNzHXds">http://t.co/AHesNzHXds</a> <span class="muted">16 days ago</span></p></div></div></div></div>
        </div><!--/row-->
    </div><!--/container-->
</div><!--/white content-->

<div id="footer">
    <div class="container">
        <div class="row">
            <div class="span8">
                <p>&copy; Copyright 2013 DesignedByDash | All rights reserved</p>
            </div><!--/span8-->
            <div class="span4">
                <ul id="footer-nav">
                    <li><a href="#">Terms</a></li>
                    <li><a href="#">Privacy</a></li>
                    <li><a href="#">FAQ</a></li>
                    <li><a href="#">Pricing</a></li>
                </ul>
            </div><!--/span4-->
        </div><!--/row-->
    </div><!--/container-->
</div><!--/footer-->