<footer id="footer">
    <div class="footer-last">
        <div class="row clearfix">
            <span class="copyright">© 2013 by <a href="http://vk.com/cawakharkov">CawaKharkov</a>. All Rights Reserved. Powered by <span class="label label-important"><a href="https://github.com/zendframework/zf2">ZF_<?php echo Zend\Version\Version::VERSION; ?></a></span>.</span>
            <div id="toTop"><i class="icon-angle-up"></i></div><!-- Back to top -->
            <div class="foot-menu">
                <ul>
                    <li><a href="<?php echo $this->url('home', ['controller' => 'news']); ?>">Новости</a></li>
                    <li><a href="<?php echo $this->url('home', ['controller' => 'news']); ?>">Новости</a></li>
                    <li><a href="<?php echo $this->url('home', ['controller' => 'news']); ?>">Новости</a></li>
                </ul><!-- end links -->
            </div><!-- end foot menu -->
        </div><!-- row -->
    </div><!-- end last -->

</footer><!-- end footer -->