<div class="sidebar-wrap">
    <h5>Categories</h5>
    <ul class="cats">
        <li><a href="typography.html">Typography</a></li>
        <li><a href="elements.html">Elements</a></li>
        <li><a href="full-width.html">Full Width</a></li>
        <li><a href="pricing-tables.html">Pricing Tables</a></li>
        <li><a href="right-sidebar.html">Right Sidebar</a></li>
        <li><a href="left-sidebar.html">Left Sidebar</a></li>
        <li><a href="404.html">404 Page</a></li>
    </ul>
</div><!--/sidebar wrap-->

<div class="sidebar-wrap">
    <h5>Text Blurb</h5>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent tempus eleifend risus ut congue. 
        Pellentesque nec lacus elit.</p>
</div><!--/sidebar wrap-->
