<div class="span4">
    <div class="def-block widget animtt" data-gen="fadeUp" style="opacity:0;">
        <h4> Категории </h4><span class="liner"></span>
        <div class="widget-content row-fluid">
            <?php echo $this->categoriesHelper(); ?>
        </div><!-- widget content -->
    </div><!-- side menu -->
    <?php
    // rand tags
    $tags = ['label-important' => 0, 'label-inverse' => 1, 'label-success' => 2, 'label-warning' => 3];
    ?>
    <?php //$this->categoriesHelper(); ?>
    <div class="def-block widget animtt" data-gen="fadeUp" style="opacity:0;">
        <h4> Популярные теги </h4><span class="liner"></span>
        <div class="widget-content row-fluid">
           <a href="#"><span class="label <?php echo array_rand($tags); ?>">Ля ля ля</span></a>
            <span class="label <?php echo array_rand($tags); ?>">Ля ля ля</span>
            <span class="label <?php echo array_rand($tags); ?>">Ля ля ля</span>
            <span class="label <?php echo array_rand($tags); ?>">Ля ля ля</span>
        </div><!-- widget content -->
    </div><!-- side tags -->
    <!-- Put this script tag to the <head> of your page -->
    <div class="def-block widget animtt" data-gen="fadeUp" style="opacity:0;">
        <h4> Комментарии </h4><span class="liner"></span>
        <div class="widget-content row-fluid">

        </div>
    </div>
</div><!-- span4 sidebar -->