<div id="header" class="animated bounceInDown">
    <div class="container">
        <div class="row">
            <div class="span12">
                <div class="navbar">
                    <div class="navbar-inner">
                        <div class="container">
                            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <a class="brand pull-left" href="index.html"><img class="logo" src="_assets/img/logo.png" alt="Converts Logo"></a>
                            <div class="nav-collapse collapse">
                                <ul class="nav pull-right">
                                    <li class="active">
                                        <a href="index.html">Home</a>
                                    </li>
                                    <li>
                                        <a href="about.html">About</a>
                                    </li>
                                    <li>
                                        <a href="blog.html">Blog</a>
                                    </li>
                                    <li class="dropdown">
                                        <a id="drop" href="work.html" role="button" class="dropdown-toggle" data-toggle="dropdown">Work <b class="caret"></b></a>
                                        <ul class="dropdown-menu" role="menu" aria-labelledby="drop">
                                            <li><a tabindex="-1" href="work-4cols.html">4 Columns</a></li>
                                            <li><a tabindex="-1" href="work-3cols.html">3 Columns</a></li>
                                            <li><a tabindex="-1" href="work-2cols.html">2 Columns</a></li>
                                            <li><a tabindex="-1" href="work-single.html">Single Work</a></li>
                                        </ul>
                                    </li>
                                    <li class="dropdown">
                                        <a id="drop" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">Features <b class="caret"></b></a>
                                        <ul class="dropdown-menu" role="menu" aria-labelledby="drop">
                                            <li><a tabindex="-1" href="typography.html">Typography</a></li>
                                            <li><a tabindex="-1" href="elements.html">Elements</a></li>
                                            <li><a tabindex="-1" href="full-width.html">Full Width</a></li>
                                            <li><a tabindex="-1" href="pricing-tables.html">Pricing Tables</a></li>
                                            <li><a tabindex="-1" href="right-sidebar.html">Right Sidebar</a></li>
                                            <li><a tabindex="-1" href="left-sidebar.html">Left Sidebar</a></li>
                                            <li><a tabindex="-1" href="404.html">404 Page</a></li>
                                        </ul>
                                    </li>
                                    <li>
                                        <a href="contact.html">Contact</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!--/span12-->
        </div><!--/row-->
    </div><!--/container-->
</div><!--/header-->