<nav>
    <ul class="sf-menu">
        <li class="current selectedLava"><a href="">Home<span class="sub">start here</span></a>
            <ul>
                <li><a href="">Home 2 - Revolution</a></li>
            </ul>
        </li>
        <li><a href="">Features<span class="sub">remix all features</span></a>
            <ul>
                <li><a href="#">Shortcodes</a>
                    <ul>
                        <li><a href="shortcode_accordion.html">Accordion</a></li>
                        <li><a href="shortcode_buttons.html">Buttons</a></li>
                        <li><a href="#">Typography</a>
                            <ul>
                                <li><a href="shortcode_columns.html">Grid Columns</a></li>
                                <li><a href="shortcode_quote.html">Quote</a></li>
                                <li><a href="shortcode_list_styles.html">List Styles</a></li>
                                <li><a href="shortcode_googlefonts.html">Google Fonts</a></li>
                                <li><a href="shortcode_dropcaps.html">Dropcaps</a></li>
                                <li><a href="shortcode_divider_lines.html">Divider Lines</a></li>
                                <li><a href="shortcode_highlights.html">Highlights</a></li>
                            </ul>
                        </li>
                        <li><a href="shortcode_tables.html">Tables</a></li>
                        <li><a href="shortcode_lightbox.html">Lightbox</a></li>
                        <li><a href="shortcode_googlemap.html">Google Map</a></li>
                        <li><a href="shortcode_video.html">Video</a></li>
                        <li><a href="shortcode_social_icons.html">Retina Social Icons</a></li>
                        <li><a href="shortcode_tab.html">Tab</a></li>
                        <li><a href="shortcode_toggle.html">Toggle</a></li>
                        <li><a href="shortcode_message_box.html">Message box</a></li>
                    </ul>
                </li>
                <li><a href="icons.html"><i class="icon-microphone mi"></i>660 Retina Icons</a></li>
                <li><a href="#"><i class="icon-caret-right mi"></i>3rd Level</a>
                    <ul>
                        <li><a href="#">1st Menu</a></li>
                        <li><a href="#">2nd Menu</a></li>
                        <li><a href="#">Another Sub</a>
                            <ul>
                                <li><a href="#">1st Menu</a></li>
                                <li><a href="#">2nd Menu</a></li>
                            </ul>
                        </li>
                    </ul>
                </li>
            </ul>
        </li>
        <li><a href="mp3s.html">MP3<span class="sub">full archive</span></a></li>
        <li><a href="videos.html">Video<span class="sub">latest clips</span></a></li>
        <li><a href="gallery4.html">Gallery<span class="sub">Photo Gallery</span></a>
            <ul>
                <li><a href="gallery4.html">Gallery 4 Column</a></li>
                <li><a href="gallery3.html">Gallery 3 Column</a></li>
                <li><a href="gallery2.html">Gallery 2 Column</a></li>
            </ul>
        </li>
        <li><a href="#">Pages<span class="sub">more templates</span></a>
            <ul>
                <li><a href="rtl.html">RTL Support</a></li>
                <li><a href="events.html">Events</a></li>
                <li><a href="mp3_single_wide.html">MP3 Single Wide</a></li>
                <li><a href="mp3_single_half.html">MP3 Single Half</a></li>
                <li><a href="video_single_wide.html">Video Single Wide</a></li>
                <li><a href="video_single_half.html">Video Single Half</a></li>
                <li><a href="fullwide.html">Fullwide Page</a></li>
                <li><a href="support_forum.html">Support Forum</a></li>
                <li><a href="contact.html">Contact</a></li>
                <li><a href="contact2.html">Contact 2</a></li>
                <li><a href="search.html">Search Result</a></li>
                <li><a href="404.html">Custom 404</a></li>
                <li><a href="archive.html">Archive</a></li>
                <li><a href="news_single.html">News Single</a></li>
            </ul>
        </li>
        <li><a href="blog-right-sidebar.html">Blog<span class="sub">latest news</span></a>
            <ul>
                <li><a href="blog-right-sidebar.html">Blog</a></li>
                <li><a href="blog-left-sidebar.html">Blog Left Sidebar</a></li>
                <li><a href="blog-both-sidebar.html">Blog Both Sidebar</a></li>
                <li><a href="blog-without-sidebar.html">Blog Without Sidebar</a></li>
                <li><a href="blog-single_wide.html">Blog Single Wide</a></li>
                <li><a href="blog-single_half.html">Blog Single Half</a></li>
                <li><a href="blog-single_facebook_comment.html">With Facebook Comment</a></li>
                <li><a href="blog-single_comment_form.html">With Comment Form</a></li>
            </ul>
        </li>
    </ul><!-- end menu -->
</nav><!-- end nav -->