<nav>
    <ul class="sf-menu">
        <li class="current selectedLava"><a href="<?php echo $this->url('home'); ?>">Главная<span class="sub">начало</span></a>
        </li>
        <li><a href="<?php echo $this->url('home',['controller'=>'gallery']); ?>">Галлерея<span class="sub">будь разной</span></a>
            <ul>
                <li><a href="#">Свадебный</a></li>
                <li><a href="#">Вечерний</a></li>
                <li><a href="#">Мужской</a></li>
            </ul>
        </li>
        <li><a href="<?php echo $this->url('home',['controller'=>'news']); ?>">Новости<span class="sub">будь в курсе</span></a></li>
        <li><a href="<?php echo $this->url('home',['controller'=>'services']); ?>">Услуги<span class="sub">прайс</span></a></li>
         <li><a href="<?php echo $this->url('home',['controller'=>'about']); ?>">Обо мне<span class="sub">история</span></a></li>
          <li><a href="<?php echo $this->url('home',['controller'=>'contact']); ?>">Контакты<span class="sub">связь со мной</span></a></li>

    </ul><!-- end menu -->
</nav><!-- end nav -->