<div class="row">	
    <div id="testimonial" class="span12">				

        <div class="white-bg">
            <img class="icon_testimonial_left" src="_assets/img/icon_testimonial_left.png" alt="Testimonial">
            <img class="icon_testimonial_right" src="_assets/img/icon_testimonial_right.png" alt="Testimonial">
            <div class="testimonials">
                <div class="testimonial-wrapper">
                    <p>Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam 
                        processus dynamicus, qui sequitur mutationem consuetudium lectorum.</p>
                    <cite>-David Bradley - NC</cite>
                </div>
                <div class="testimonial-wrapper" style="display: none;">
                    <p>Mauris lobortis ipsum magna. Integer auctor fringilla tellus sed aliquet. In egestas, lacus sed elementum hendrerit, leo urna sodales tortor.</p>
                    <cite>-Ashley Peacock - UK</cite>
                </div>
                <div class="testimonial-wrapper" style="display: none;">
                    <p>Mauris lobortis ipsum magna. Integer auctor fringilla tellus sed aliquet. In egestas, lacus sed elementum hendrerit, leo urna sodales tortor.</p>
                    <cite>-Another Person - IN</cite>
                </div>
                <div class="testimonial-wrapper" style="display: none;">
                    <p>In hac habitasse platea dictumst. Nullam nec ligula eget lorem tincidunt gravida non ac sem. Curabitur vel felis in metus aliquet iaculis at nec erat.</p>
                    <cite>-Final Pesron - JP</cite>
                </div>
            </div>
        </div><!--/white bg-->
    </div><!--/span12-->
</div>  