<!--LayerSlider begin-->
<div class="container">
    <div id="layerslider" style="width: 100%; height: 500px; margin: 0px auto;">

        <!--LayerSlider layer-->
        <div class="ls-layer">

            <!--LayerSlider sublayers-->
            <h3 class="ls-s3" style="left: 20px; top: 80px; slidedirection: top; easingin: easeOutQuint;">Предалагаю Вам<br />Услуги профессионального визажиста:</h3>
            <img class="ls-s3" src="_assets/img/slides/slide2.png" alt="" style="delayin: 1500; left: 550px; top: 50px; slidedirection: right;" />
            <ul class="ls-s3 ls-dbd-list" style="left: 35px; top: 165px; delayin: 800; slidedirection: left;">
                <li><img src="_assets/img/check-icon.png" class="list-image" /> Дневной, деловой макияж</li>
                <li><img src="_assets/img/check-icon.png" class="list-image" /> Вечерний макияж</li>
                <li><img src="_assets/img/check-icon.png" class="list-image" /> Свадебный макияж</li>
                <li><img src="_assets/img/check-icon.png" class="list-image" /> Возростной макияж</li>
                <li><img src="_assets/img/check-icon.png" class="list-image" /> Мужской макияж</li>
                <li><img src="_assets/img/check-icon.png" class="list-image" /> Макияж для фото-видео сьемок</li>
                <li><img src="_assets/img/check-icon.png" class="list-image" /> Детский макияж</li>
                <li><img src="_assets/img/check-icon.png" class="list-image" /> Подиумный макияж</li>
                <li><img src="_assets/img/check-icon.png" class="list-image" /> Наращивание ресниц</li>
                <li><img src="_assets/img/check-icon.png" class="list-image" /> Корекция бровей</li>
                
            </ul>

            <a class="ls-s3 blue-btn" style="top: 385px; left: 40px; delayin: 2500; slidedirection: bottom; easingin: easeInQuint;">Buy This Theme Now!</a>

        </div>
        <div class="ls-layer">
            <h3 class="ls-s3" style="left: 20px; top: 80px; slidedirection: left;">BEAUTIFUL ON EVERY<br />SCREEN</h3>
            <p class="ls-s3" style="left: 20px; top: 160px; delayin: 800; slidedirection: left;">Responsive theme that will look good on any device.<br />Don't believe us? Check it out for<br /> 
                yourself today.</p>
            <img class="ls-s3" src="_assets/img/slides/slide-2-img.png" alt="" style="top: 100px; left: 370px; delayin: 2700; slidedirection: right; easeingin: easeInCirc;" />

            <ul class="ls-s3 ls-dbd-list" style="left: 35px; top: 240px; delayin: 1800; slidedirection: left;">
                <li><img src="_assets/img/check-icon.png" class="list-image" /> Desktop</li>
                <li><img src="_assets/img/check-icon.png" class="list-image" /> iPhone</li>
                <li><img src="_assets/img/check-icon.png" class="list-image" /> iPad</li>
                <li><img src="_assets/img/check-icon.png" class="list-image" /> Other Mobile Devices</li>
            </ul>
        </div>

        <div class="ls-layer">
            <h3 class="ls-s3" style="left: 20px; top: 140px; slidedirection: bottom;">THIS IS THE APP YOU'VE BEEN WAITING<br />ON YOUR WHOLE LIFE</h3>
            <p class="ls-s3" style="left: 20px; top: 220px; delayin: 800; slidedirection: bottom;">I'm not honestly sure how you’ve lived without this app your entire life. If I was you I<br />would stop reading this and go and head scroll down so you can sign up for this bad boy. So<br />get going, becase you’re only wasting both of our time.</p>

            <img class="ls-s3" src="_assets/img/slides/slide-3-img.png" alt="" style="top: 30px; left: 710px; delayin: 1800; slidedirection: top;" />

            <a class="blue-btn ls-s3" style="top: 310px; left: 20px; delayin: 2500; slidedirection: bottom;">Get Started Today</a>
        </div>

    </div>
    <!--LayerSlider end-->
</div>
