<div class="sliderr">
    <div class="fullwidthbanner-container">					
        <div class="revolution">
            <ul>
                <li data-transition="random" data-slotamount="7" data-masterspeed="300" >
                    <img src="/img/slides/new/slide1.jpg" alt="slider" >

                    <div class="tp-caption fade"  
                         data-x="-200" 
                         data-y="450" 
                         data-speed="300" 
                         data-start="800" 
                         data-easing="easeInOutExpo"  ><img src="/img/slides/slide1-cap1.png" alt="Image 2"></div>

                <!--    <div class="tp-caption sfl"   
                         data-x="-200" 
                         data-y="450" 
                         data-speed="300" 
                         data-start="1200" 
                         data-easing="easeInOutExpo"  ><img src="/img/slides/slide1-cap2.png" alt="Image 3"></div>
                -->
                    <div class="tp-caption sfr"  
                         data-x="-57" 
                         data-y="450" 
                         data-speed="300" 
                         data-start="1200" 
                         data-easing="easeInOutExpo"  ><img src="/img/slides/slide1-cap3.png" alt="Image 4"></div>

                    <div class="tp-caption sfr"  
                         data-x="-70" 
                         data-y="510" 
                         data-speed="300" 
                         data-start="2000" 
                         data-easing="easeInOutExpo"  ><a href="mp3_single_half.html"><img src="/img/slides/slide1-cap4.png" alt="Image 5"></a></div>

                    <div class="tp-caption sfl"  
                         data-x="-65" 
                         data-y="510" 
                         data-speed="300" 
                         data-start="2000" 
                         data-easing="easeInOutExpo"  ><img src="/img/slides/slide1-cap5.png" alt="Image 6"></div>
                </li>

                <li data-transition="random" data-slotamount="7" data-masterspeed="300" >
                    <img src="/img/slides/new/slide2.jpg" alt="slider2" >

                    <div class="tp-caption big_black randomrotate"  
                         data-x="603" 
                         data-y="384" 
                         data-speed="500" 
                         data-start="1200" 
                         data-easing="easeInOutExpo"  >Responsive Design</div>

                    <div class="tp-caption big_orange randomrotate"  
                         data-x="701" 
                         data-y="328" 
                         data-speed="500" 
                         data-start="1700" 
                         data-easing="easeInOutExpo"  >Retina Ready</div>
                </li>

                <li data-transition="random" data-slotamount="7" data-masterspeed="300" >
                    <img src="/img/slides/new/slide3.jpg" alt="slider3" >

                    <div class="tp-caption large_text randomrotate"  
                         data-x="559" 
                         data-y="253" 
                         data-speed="500" 
                         data-start="1000" 
                         data-easing="easeInOutExpo"  >Revolution Slider</div>

                    <div class="tp-caption medium_text randomrotate"  
                         data-x="563" 
                         data-y="313" 
                         data-speed="500" 
                         data-start="1500" 
                         data-easing="easeInOutExpo"  >Awesome MusicPlayer</div>

                    <div class="tp-caption medium_text randomrotate"  
                         data-x="565" 
                         data-y="345" 
                         data-speed="500" 
                         data-start="2000" 
                         data-easing="easeInOutExpo"  >Wonderful Gallery</div>

                    <div class="tp-caption medium_text randomrotate"  
                         data-x="567" 
                         data-y="377" 
                         data-speed="500" 
                         data-start="2500" 
                         data-easing="easeInOutExpo"  >Seo Optimized</div>

                    <div class="tp-caption small_text randomrotate"  
                         data-x="566" 
                         data-y="407" 
                         data-speed="500" 
                         data-start="3000" 
                         data-easing="easeInOutExpo"  >and Much More ...</div>
                </li>

                     <li data-transition="random" data-slotamount="7" data-masterspeed="300" >
                    <img src="/img/slides/new/slide4.jpg" alt="slider3" >

                    <div class="tp-caption large_text randomrotate"  
                         data-x="-150" 
                         data-y="253" 
                         data-speed="500" 
                         data-start="1000" 
                         data-easing="easeInOutExpo"  >Revolution Slider</div>

                    <div class="tp-caption medium_text randomrotate"  
                         data-x="-150" 
                         data-y="313" 
                         data-speed="500" 
                         data-start="1500" 
                         data-easing="easeInOutExpo"  >Awesome MusicPlayer</div>

            </ul><!-- End Slides -->
            <div class="tp-bannertimer"></div><!-- Timer -->										
        </div>					
    </div>
</div>