<div class="sliderr">
    <div class="fullwidthbanner-container">					
        <div class="revolution">
            <ul>
                <li data-transition="random" data-slotamount="7" data-masterspeed="300" >
                    <img src="/img/slides/new/slide1.jpg" alt="slider" >

                 
                    <div class="tp-caption sfl big_black randomrotate"   
                         data-x="-200" 
                         data-y="450" 
                         data-speed="350" 
                         data-start="1200" 
                         data-easing="easeInOutExpo"  >Дневной макияж</div>
                
                   
                    <div class="tp-caption sfr"  
                         data-x="-70" 
                         data-y="510" 
                         data-speed="300" 
                         data-start="2000" 
                         data-easing="easeInOutExpo"  ><img src="/img/slides/slide1-cap4.png" alt="Image 5"></div>

                    <div class="tp-caption sfl"  
                         data-x="-65" 
                         data-y="510" 
                         data-speed="300" 
                         data-start="2000" 
                         data-easing="easeInOutExpo"  ><img src="/img/slides/slide1-cap5.png" alt="Image 6"></div>
                </li>

                <li data-transition="random" data-slotamount="7" data-masterspeed="300" >
                    <img src="/img/slides/new/slide2.jpg" alt="slider2" >

                    <div class="tp-caption big_black randomrotate"  
                         data-x="603" 
                         data-y="384" 
                         data-speed="500" 
                         data-start="1200" 
                         data-easing="easeInOutExpo"  >Вечерний макияж</div>

                    <div class="tp-caption big_orange randomrotate"  
                         data-x="701" 
                         data-y="328" 
                         data-speed="500" 
                         data-start="1700" 
                         data-easing="easeInOutExpo"  >Будь превосхода</div>
                </li>

                <li data-transition="random" data-slotamount="7" data-masterspeed="300" >
                    <img src="/img/slides/new/slide3.jpg" alt="slider3" >

                    <div class="tp-caption randomrotate big_black"  
                         data-x="559" 
                         data-y="233" 
                         data-speed="500" 
                         data-start="1000" 
                         data-easing="easeInOutExpo"  >Выбери свой</div>

                    <div class="tp-caption medium_text randomrotate big_white"  
                         data-x="563" 
                         data-y="300" 
                         data-speed="500" 
                         data-start="1500" 
                         data-easing="easeInOutExpo"  >Дневной</div>
                    
                    
                    <div class="tp-caption medium_text randomrotate big_white"  
                         data-x="566" 
                         data-y="350" 
                         data-speed="500" 
                         data-start="2000" 
                         data-easing="easeInOutExpo"  >Вечерний</div>

                    <div class="tp-caption medium_text randomrotate big_white"  
                         data-x="565" 
                         data-y="400" 
                         data-speed="500" 
                         data-start="2500" 
                         data-easing="easeInOutExpo"  >Свадебный</div>

                     <div class="tp-caption medium_text randomrotate big_white"  
                         data-x="566" 
                         data-y="450" 
                         data-speed="500" 
                         data-start="3000" 
                         data-easing="easeInOutExpo"  >Подиумный</div>
                </li>

                     <li data-transition="random" data-slotamount="7" data-masterspeed="300" >
                    <img src="/img/slides/new/slide4.jpg" alt="slider3" >

                    <div class="tp-caption large_text randomrotate"  
                         data-x="-150" 
                         data-y="253" 
                         data-speed="500" 
                         data-start="1000" 
                         data-easing="easeInOutExpo"  >Порази всех</div>

                    <div class="tp-caption medium_text randomrotate"  
                         data-x="-150" 
                         data-y="313" 
                         data-speed="500" 
                         data-start="1500" 
                         data-easing="easeInOutExpo"  >Будь уникальна</div>

            </ul><!-- End Slides -->
            <div class="tp-bannertimer"></div><!-- Timer -->										
        </div>					
    </div>
</div>