<?php //$form->setAttribute('action', $this->url('application',['controller'=>'upload','action'=>'upload'])); ?>
<?php $form->prepare(); // The correct enctype is set here ?>
<?php echo $this->form()->openTag($form); ?>

    <div class="form-element">
        <?php $fileElement = $form->get('image-file'); ?>
        <?php echo $this->formLabel($fileElement); ?>
        <?php echo $this->formFile($fileElement); ?>
        <?php echo $this->formElementErrors($fileElement); ?>
        <?php echo $this->formSubmit($form->get('submit')); ?>
    </div>

<?php echo $this->form()->closeTag(); ?>
