<?php echo $this->doctype(); ?>
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle() ?>
        <?php echo $this->headMeta() ?>

        <?php echo $this->headLink(); ?>
        <!--[if lt IE 9]>
                <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->    
        <!--[if gte IE 9]>
      <link type="text/css" rel="stylesheet" href="_assets/css/ie9-gradients.css" />
      <![endif]-->
    </head>
    <body>

        <?php echo $this->partial('partials/navigation'); ?>

        <div id="hero">
            <?php if ($this->controllerName() == 'Application\Controller\Index') {
                echo $this->partial('partials/slider');
            } ?>

        </div><!--/hero-->
        <div id="callout">
            <div class="container">
                <div class="pull-left">
                    <h4>Есть много вариантов Lorem Ipsum</h4>
                    <p>Если вам нужен Lorem Ipsum для серьёзного проекта.</p>               </div>
                <div class="pull-right">
                    <a class="blue-btn ie8-btn-fix" href="#">Согласен</a>
                </div>
            </div>
        </div>
        <div id="content">
            <div class="container">
                <div class="row">
                       <div class="span9">
                    <?php echo $this->content; ?>
                           </div>
                <div class="span3">
                    <?php echo $this->partial('partials/leftSidebar'); ?>
                </div>
                   </div> 
            </div><!--/container-->
        </div><!--/content-->

        <?php echo $this->partial('partials/footer'); ?>

<?php echo $this->headScript(); ?>

        <!-- slider settings-->
        <script type="text/javascript">
            jQuery(document).ready(function() {
                jQuery('#layerslider').layerSlider({
                    responsiveUnder: 980,
                    sublayerContainer: 940,
                    skinsPath: '_assets/js/layerslider/skins/',
                    skin: 'fullwidth',
                    thumbnailNavigation: 'hover',
                    responsive: false,
                    slideDirection: 'left',
                    delayin: 1000
                });
            });
        </script>

    </body>
</html>