<div class="well" style="padding: 8px 0;">
    <ul class="nav nav-list">
        <li class="nav-header">Навигация</li>
        <li>
            <a href="<?php echo $this->url('admin',['controller'=>'posts']) ?>"><i class="icon-folder-open"></i>Записи</a>
        </li>
        <li>
            <a href="<?php echo $this->url('admin',['controller'=>'categories']) ?>"><i class="icon-folder-open"></i>Категории</a>
        </li>
    </ul>
</div>