<div class="well" style="padding: 8px 0;">
    <ul class="nav nav-list">
        <li class="nav-header">
            Zf2 blog
        </li>
        <li>
            <a href="<?php echo $this->url('admin',['controller'=>'posts']) ?>"><i class="icon-folder-open"></i>Posts</a>
        </li>
        <li>
            <a href="<?php echo $this->url('admin',['controller'=>'categories']) ?>"><i class="icon-folder-open"></i>Categories</a>
        </li>

        <li class="nav-header">
            Your Account
        </li>
        <li>
            <a href="profile#"><i class="icon-user"></i> Profile</a>
        </li>
        <li>
            <a href="settings#"><i class="icon-cog"></i> Settings</a>
        </li>
        <li class="divider">
        </li>
        <li>
            <a href="help#"><i class="icon-info-sign"></i> Help</a>
        </li>
        <li class="nav-header">
            Bonus Templates
        </li>
        <li>
            <a href="gallery#"><i class="icon-picture"></i> Gallery</a>
        </li>
        <li>
            <a href="blank#"><i class="icon-stop"></i> Blank Slate</a>
        </li>
    </ul>
</div>