<div class="well" style="padding: 8px 0;">
    <ul class="nav nav-list">
        <li class="nav-header">Навигация</li>
        <hr>
        <li>
            <a href="<?php echo $this->url('admin',['controller'=>'posts']) ?>"><i class="icon-book"></i>Записи</a>
        </li>
        <li>
            <a href="<?php echo $this->url('admin',['controller'=>'categories']) ?>"><i class="icon-list"></i>Категории</a>
        </li>
        <li>
            <a href="<?php echo $this->url('admin',['controller'=>'gallery']) ?>"><i class="icon-th"></i>Галерея</a>
        </li>
        <li>
            <a href="<?php echo $this->url('admin',['controller'=>'review']) ?>"><i class="icon-user"></i>Отзывы</a>
        </li>
    </ul>
</div>