<?php foreach ($posts as $post): ?>
<div class="span3">
    <?php //var_dump($post->getThubnail());//die(); ?>
    <img alt="work" src="<?php //var_dump($expression) ?>">
    <div class="white-bg box-top-fix">
        <h5><?php echo $post->getTitle(); ?></h5>
        <p><?php echo substr($post->getText(),0,50); ?>...</p>
        <p>Posted:<?php echo $post->getCreatedAt()->format("F j, Y, g:i a"); ?></p>
        <a href="#">Read More →</a>
    </div><!--/work bg-->
</div>
<?php endforeach; ?>