<h2>Создать запись</h2>
<script src="/js/tinymce/tinymce.min.js"></script>
<script type="text/javascript">
    tinymce.init({
        selector: "textarea"
    });
</script>
<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('admin', ['controller' => 'posts',
            'action' => 'create']));
?>

<?php echo $this->form()->openTag($form) ?>
<div class="form_element">
    <?php foreach ($form as $element): ?>
        <?php echo $this->formRow($element); ?>
        <?php echo $this->formElementerrors($element); ?>
        <?php endforeach; ?>
</div>
<?php echo $this->form()->closeTag() ?>