<h2>Просмотр записи</h2>
<?= $this->flashmessengerHelper() ?>
<script src="/js/tinymce/tinymce.min.js"></script>
<script type="text/javascript">
    tinymce.init({
        selector: "textarea",
        height : 350,
        plugins: [
            "advlist autolink lists link image charmap print preview hr anchor pagebreak",
            "searchreplace wordcount visualblocks visualchars code fullscreen",
            "insertdatetime media nonbreaking save table contextmenu directionality",
            "emoticons template paste textcolor"
        ],
        toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
        toolbar2: "print preview media | forecolor backcolor emoticons",
        image_advtab: true,
        templates: [
            {title: 'Test template 1', content: 'Test 1'},
            {title: 'Test template 2', content: 'Test 2'}
        ]
    });


</script>
<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('admin', ['controller' => 'posts',
            'action' => 'create']));
?>

<?php echo $this->form()->openTag($form) ?>

<?php foreach ($form as $element): ?>
    <?php if (!$element instanceof Zend\Form\Element\Submit): ?>
        <div class="control-group">
            <?php echo $this->formLabel($element); ?>
            <div class="controls">
                <?php echo $this->formElement($element); ?>
                <?php echo $this->formElementerrors($element); ?>
            </div>
        </div>
    <?php else: ?>
        <div class="form-actions">
            <?php echo $this->formRow($element); ?>
            <?php echo $this->formElementerrors($element); ?>
        </div>
    <?php endif; ?>
<?php endforeach; ?>

<?php echo $this->form()->closeTag() ?>
